name: Build

on:
  workflow_dispatch:
#  push:
#    branches:
#      - main

permissions:
  contents: write

jobs:


  # Windows x86-64

  windows-x86_64:
    runs-on: windows-2025

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r libraries.txt
          pip install pyinstaller

      - name: Building Executables
        run: |
          pyinstaller --onefile --noconsole --add-data "gamzylogo.png;." --icon "gamzylogo.ico" --hidden-import=desktop_notifier.resources --name GamzScript script.py
          pyinstaller --onefile --noconsole --add-data "gamzylogo.png;." --add-data "steamlogo.png;." --add-data "epiclogo.png;." --add-data "goglogo.png;." --add-data "itchlogo.png;." --add-data "ubilogo.png;." --add-data "Minecraftia-Regular.ttf;." --icon "gamzylogo.ico" --name Gamzy main.py

      - name: Building Installer
        run: |
          iscc setup-x86_64.iss

      - name: Uploading Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          $tag = gh release view --json tagName --jq .tagName
          gh release upload $tag output/Gamzy-Setup-Windows-x86_64.exe --clobber


  # Windows ARM64
  
  windows-ARM64:
    runs-on: windows-11-arm

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r libraries.txt
          pip install pyinstaller

      - name: Building Executables
        run: |
          pyinstaller --onefile --noconsole --add-data "gamzylogo.png;." --icon "gamzylogo.ico" --hidden-import=desktop_notifier.resources --name GamzScript script.py
          pyinstaller --onefile --noconsole --add-data "gamzylogo.png;." --add-data "steamlogo.png;." --add-data "epiclogo.png;." --add-data "goglogo.png;." --add-data "itchlogo.png;." --add-data "ubilogo.png;." --add-data "Minecraftia-Regular.ttf;." --icon "gamzylogo.ico" --name Gamzy main.py

      - name: Building Installer
        run: |
          iscc setup-ARM64.iss
      
      - name: Uploading Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          $tag = gh release view --json tagName --jq .tagName
          gh release upload $tag output/Gamzy-Setup-Windows-ARM64.exe --clobber


  # Linux x86-64
  
  linux-x86_64:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r libraries.txt
          pip install pyinstaller

      - name: Building Executables
        run: |
          pyinstaller --onefile --noconsole --add-data "gamzylogo.png:." --icon "gamzylogo.ico" --hidden-import=desktop_notifier.resources --name GamzScript script.py
          pyinstaller --onefile --noconsole --add-data "gamzylogo.png:." --add-data "steamlogo.png:." --add-data "epiclogo.png:." --add-data "goglogo.png:." --add-data "itchlogo.png:." --add-data "ubilogo.png:." --add-data "uninstall.png:." --add-data "Minecraftia-Regular.ttf:." --add-data "linuxGamzyUpdate.sh.template:." --add-data "linuxUninstall.sh:." --add-data "GamzScript.desktop.template:." --icon "gamzylogo.ico" --name Gamzy main.py

      - name: Building Linux package
        run: |
          mkdir -p package/Gamzy
          mkdir -p output
      
          cp dist/Gamzy package/Gamzy/
          cp dist/GamzScript package/Gamzy/
          cp "Create Shortcut.sh" package/Gamzy/
      
          chmod +x package/Gamzy/Gamzy
          chmod +x package/Gamzy/GamzScript
          chmod +x "package/Gamzy/Create Shortcut.sh"
      
          tar -czf output/Gamzy-Linux-x86_64.tar.gz -C package Gamzy
      
      - name: Uploading Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          tag=$(gh release view --json tagName --jq .tagName)
          gh release upload "$tag" output/Gamzy-Linux-x86_64.tar.gz --clobber


  # Linux ARM64
  
  linux-ARM64:
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r libraries.txt
          pip install pyinstaller

      - name: Building Executables
        run: |
          pyinstaller --onefile --noconsole --add-data "gamzylogo.png:." --icon "gamzylogo.ico" --hidden-import=desktop_notifier.resources --name GamzScript script.py
          pyinstaller --onefile --noconsole --add-data "gamzylogo.png:." --add-data "steamlogo.png:." --add-data "epiclogo.png:." --add-data "goglogo.png:." --add-data "itchlogo.png:." --add-data "ubilogo.png:." --add-data "uninstall.png:." --add-data "Minecraftia-Regular.ttf:." --add-data "linuxGamzyUpdate.sh.template:." --add-data "linuxUninstall.sh:." --add-data "GamzScript.desktop.template:." --icon "gamzylogo.ico" --name Gamzy main.py

      - name: Building Linux package
        run: |
          mkdir -p package/Gamzy
          mkdir -p output
      
          cp dist/Gamzy package/Gamzy/
          cp dist/GamzScript package/Gamzy/
          cp "Create Shortcut.sh" package/Gamzy/
      
          chmod +x package/Gamzy/Gamzy
          chmod +x package/Gamzy/GamzScript
          chmod +x "package/Gamzy/Create Shortcut.sh"
      
          tar -czf output/Gamzy-Linux-ARM64.tar.gz -C package Gamzy
      
      - name: Uploading Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          tag=$(gh release view --json tagName --jq .tagName)
          gh release upload "$tag" output/Gamzy-Linux-ARM64.tar.gz --clobber
